In [202]:
import pandas as pd
import datetime
import numpy as np

In [229]:
doorA_lambda = 50
doorB_lambda = 70
doorC_lambda = 28
doorD_lambda = 100
doorE_lambda = 42

dt = datetime.datetime(2015, 1, 1)
end = datetime.datetime(2017, 12, 31, 23, 59, 59)
step = datetime.timedelta(minutes = 30)
dif = (end-dt).days+1

num_time = dif*24*2
A = np.random.poisson(doorA_lambda, num_time)
B = np.random.poisson(doorB_lambda, num_time)
C = np.random.poisson(doorC_lambda, num_time)
D = np.random.poisson(doorD_lambda, num_time)
E = np.random.poisson(doorE_lambda, num_time)

In [230]:
minHour = 8
maxHour = 21
sigma = 1
mu = 14.5
result = []
i = 0
while dt < end:
    result.append(dt.strftime('%Y-%m-%d %H:%M'))
    x = dt.hour
    p = np.exp(-np.power((x-mu),2)/(2*np.power(sigma,2)))/np.sqrt(2*np.pi*np.power(sigma,2))+1
    if dt.hour<minHour or dt.hour>=maxHour:
        A[i]=B[i]=C[i]=D[i]=E[i]=0
    if dt.weekday()>3: #Weekend
        A[i]=int(A[i]*1.2)
        B[i]=int(B[i]*1.2)
        C[i]=int(C[i]*1.2)
        D[i]=int(D[i]*1.2)
        E[i]=int(E[i]*1.2)
#     if dt.hour<11 or dt.hour>19: #Very early or very late
    A[i]=int(A[i]*p)
    B[i]=int(B[i]*p)
    C[i]=int(C[i]*p)
    D[i]=int(D[i]*p)
    E[i]=int(E[i]*p)        
    i += 1
    dt += step

In [231]:
mall_data = pd.concat([pd.DataFrame(result),pd.DataFrame(A),pd.DataFrame(B),pd.DataFrame(C), pd.DataFrame(D), pd.DataFrame(E)], axis = 1)

In [232]:
mall_data.columns = ['Date', 'DoorA', 'DoorB', 'DoorC', 'DoorD', 'DoorE']
mall_data

                  Date  DoorA  DoorB  DoorC  DoorD  DoorE
0     2017-07-01 00:00      0      0      0      0      0
1     2017-07-01 00:30      0      0      0      0      0
2     2017-07-01 01:00      0      0      0      0      0
3     2017-07-01 01:30      0      0      0      0      0
4     2017-07-01 02:00      0      0      0      0      0
5     2017-07-01 02:30      0      0      0      0      0
6     2017-07-01 03:00      0      0      0      0      0
7     2017-07-01 03:30      0      0      0      0      0
8     2017-07-01 04:00      0      0      0      0      0
9     2017-07-01 04:30      0      0      0      0      0
10    2017-07-01 05:00      0      0      0      0      0
11    2017-07-01 05:30      0      0      0      0      0
12    2017-07-01 06:00      0      0      0      0      0
13    2017-07-01 06:30      0      0      0      0      0
14    2017-07-01 07:00      0      0      0      0      0
15    2017-07-01 07:30      0      0      0      0      0
16    2017-07-01 08:00     62     73     27    134     48
17    2017-07-01 08:30     57     90     28    121     45
18    2017-07-01 09:00     66     82     40    109     54
19    2017-07-01 09:30     42     91     37    118     44
20    2017-07-01 10:00     48     85     39    120     50
21    2017-07-01 10:30     74     76     40    126     50
22    2017-07-01 11:00     56     84     33    127     37
23    2017-07-01 11:30     60     79     30    114     42
24    2017-07-01 12:00     61    103     25    119     52
25    2017-07-01 12:30     71    106     37    104     57
26    2017-07-01 13:00     72     79     47    128     65
27    2017-07-01 13:30     70     99     36    128     65
28    2017-07-01 14:00     97    102     45    175     62
29    2017-07-01 14:30     73    116     45    139     58
...                ...    ...    ...    ...    ...    ...
2946  2017-08-31 09:00     45     87     29    100     49
2947  2017-08-31 09:30     54     64     29     93     41
2948  2017-08-31 10:00     55     53     23     98     39
2949  2017-08-31 10:30     37     92     30     97     39
2950  2017-08-31 11:00     57     65     30     83     36
2951  2017-08-31 11:30     48     72     27    107     49
2952  2017-08-31 12:00     56     68     30     86     43
2953  2017-08-31 12:30     68     63     25     98     39
2954  2017-08-31 13:00     65     64     23    119     47
2955  2017-08-31 13:30     67     73     38    124     38
2956  2017-08-31 14:00     66     93     36    135     54
2957  2017-08-31 14:30     77     93     29    147     50
2958  2017-08-31 15:00     62     77     44    125     63
2959  2017-08-31 15:30     60     91     39    123     48
2960  2017-08-31 16:00     47     85     25    109     48
2961  2017-08-31 16:30     58     55     27    116     42
2962  2017-08-31 17:00     62     60     25     94     33
2963  2017-08-31 17:30     49     76     27     94     33
2964  2017-08-31 18:00     52     68     21    127     48
2965  2017-08-31 18:30     34     69     30    102     39
2966  2017-08-31 19:00     52     75     34    118     37
2967  2017-08-31 19:30     53     81     28    104     51
2968  2017-08-31 20:00     43     73     20     97     53
2969  2017-08-31 20:30     61     62     25    113     46
2970  2017-08-31 21:00      0      0      0      0      0
2971  2017-08-31 21:30      0      0      0      0      0
2972  2017-08-31 22:00      0      0      0      0      0
2973  2017-08-31 22:30      0      0      0      0      0
2974  2017-08-31 23:00      0      0      0      0      0
2975  2017-08-31 23:30      0      0      0      0      0

[2976 rows x 6 columns]

In [233]:
melted = pd.melt(mall_data, id_vars=['Date'], var_name='Door', value_name='Count')

In [234]:
df = melted.sort_values(by = ['Date', 'Door']).reset_index(drop = True)

In [235]:
df.to_csv("door_data.csv")

In [133]:
np.power(3,2)

9

In [224]:
dif.days

61