In [1]:
import pandas as pd
import datetime
import numpy as np

In [178]:
doorA_lambda = 50
doorB_lambda = 70
doorC_lambda = 28
doorD_lambda = 100
doorE_lambda = 42

num_time = 31*24*2
A = np.random.poisson(doorA_lambda, num_time)
B = np.random.poisson(doorB_lambda, num_time)
C = np.random.poisson(doorC_lambda, num_time)
D = np.random.poisson(doorD_lambda, num_time)
E = np.random.poisson(doorE_lambda, num_time)

In [179]:
dt = datetime.datetime(2017, 07, 01)
end = datetime.datetime(2017, 07, 31, 23, 59, 59)
step = datetime.timedelta(minutes = 30)

minHour = 8
maxHour = 21
sigma = 1
mu = 14.5
result = []
i = 0
while dt < end:
    result.append(dt.strftime('%Y-%m-%d %H:%M'))
    x = dt.hour
    p = np.exp(-np.power((x-mu),2)/(2*np.power(sigma,2)))/np.sqrt(2*np.pi*np.power(sigma,2))+1
    if dt.hour<minHour or dt.hour>=maxHour:
        A[i]=B[i]=C[i]=D[i]=E[i]=0
    if dt.weekday()>3: #Weekend
        A[i]=int(A[i]*1.2)
        B[i]=int(B[i]*1.2)
        C[i]=int(C[i]*1.2)
        D[i]=int(D[i]*1.2)
        E[i]=int(E[i]*1.2)
#     if dt.hour<11 or dt.hour>19: #Very early or very late
    A[i]=int(A[i]*p)
    B[i]=int(B[i]*p)
    C[i]=int(C[i]*p)
    D[i]=int(D[i]*p)
    E[i]=int(E[i]*p)        
    i += 1
    dt += step

In [180]:
mall_data = pd.concat([pd.DataFrame(result),pd.DataFrame(A),pd.DataFrame(B),pd.DataFrame(C), pd.DataFrame(D), pd.DataFrame(E)], axis = 1)

In [181]:
mall_data.columns = ['Date', 'DoorA', 'DoorB', 'DoorC', 'DoorD', 'DoorE']
mall_data

                  Date  DoorA  DoorB  DoorC  DoorD  DoorE
0     2017-07-01 00:00      0      0      0      0      0
1     2017-07-01 00:30      0      0      0      0      0
2     2017-07-01 01:00      0      0      0      0      0
3     2017-07-01 01:30      0      0      0      0      0
4     2017-07-01 02:00      0      0      0      0      0
5     2017-07-01 02:30      0      0      0      0      0
6     2017-07-01 03:00      0      0      0      0      0
7     2017-07-01 03:30      0      0      0      0      0
8     2017-07-01 04:00      0      0      0      0      0
9     2017-07-01 04:30      0      0      0      0      0
10    2017-07-01 05:00      0      0      0      0      0
11    2017-07-01 05:30      0      0      0      0      0
12    2017-07-01 06:00      0      0      0      0      0
13    2017-07-01 06:30      0      0      0      0      0
14    2017-07-01 07:00      0      0      0      0      0
15    2017-07-01 07:30      0      0      0      0      0
16    2017-07-01 08:00     26     43     13     58     22
17    2017-07-01 08:30     30     42     16     70     30
18    2017-07-01 09:00     24     46     18     61     28
19    2017-07-01 09:30     31     47     19     68     24
20    2017-07-01 10:00     33     43     14     61     24
21    2017-07-01 10:30     33     42     14     45     19
22    2017-07-01 11:00     27     42     18     58     25
23    2017-07-01 11:30     25     45     17     60     20
24    2017-07-01 12:00     31     48     16     67     20
25    2017-07-01 12:30     32     34     19     57     22
26    2017-07-01 13:00     32     56     16     70     35
27    2017-07-01 13:30     36     58     22     70     30
28    2017-07-01 14:00     46     67     30     87     42
29    2017-07-01 14:30     57     85     20     92     42
...                ...    ...    ...    ...    ...    ...
1458  2017-07-31 09:00     24     36     15     48     20
1459  2017-07-31 09:30     26     33     17     56     23
1460  2017-07-31 10:00     24     29     12     48     20
1461  2017-07-31 10:30     24     38     10     48     25
1462  2017-07-31 11:00     26     35     13     64     17
1463  2017-07-31 11:30     24     28     12     55     18
1464  2017-07-31 12:00     26     33     12     61     23
1465  2017-07-31 12:30     29     35      8     60     18
1466  2017-07-31 13:00     18     46     20     62     25
1467  2017-07-31 13:30     35     44     21     54     21
1468  2017-07-31 14:00     39     65     29     89     34
1469  2017-07-31 14:30     51     62     18     86     33
1470  2017-07-31 15:00     34     61     30     86     28
1471  2017-07-31 15:30     30     61     25     77     36
1472  2017-07-31 16:00     28     40     23     62     27
1473  2017-07-31 16:30     27     51     16     74     25
1474  2017-07-31 17:00     22     33     16     57     22
1475  2017-07-31 17:30     31     42     12     52     20
1476  2017-07-31 18:00     22     33      8     39     20
1477  2017-07-31 18:30     26     40     14     49     25
1478  2017-07-31 19:00     21     38     17     58     20
1479  2017-07-31 19:30     25     33     13     44     22
1480  2017-07-31 20:00     27     30     11     54     17
1481  2017-07-31 20:30     26     35     13     49     15
1482  2017-07-31 21:00      0      0      0      0      0
1483  2017-07-31 21:30      0      0      0      0      0
1484  2017-07-31 22:00      0      0      0      0      0
1485  2017-07-31 22:30      0      0      0      0      0
1486  2017-07-31 23:00      0      0      0      0      0
1487  2017-07-31 23:30      0      0      0      0      0

[1488 rows x 6 columns]

In [182]:
melted = pd.melt(mall_data, id_vars=['Date'], var_name='Door', value_name='Count')

In [183]:
df = melted.sort_values(by = ['Date', 'Door']).reset_index(drop = True)

In [184]:
df.to_csv("door_data.csv")

In [133]:
np.power(3,2)

9